# Generated by Django 4.1.13 on 2024-04-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion1', models.IntegerField(max_length=300)),
                ('criterion2', models.IntegerField(max_length=300)),
                ('criterion3', models.IntegerField(max_length=300)),
                ('criterion4', models.IntegerField(max_length=300)),
                ('criterion5', models.IntegerField(max_length=300)),
                ('criterion6', models.IntegerField(max_length=300)),
                ('criterion7', models.IntegerField(max_length=300)),
                ('comment', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
