# Generated by Django 4.1.13 on 2024-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='criterion1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='criterion2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='criterion3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='criterion4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='criterion5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='criterion6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='criterion7',
            field=models.IntegerField(),
        ),
    ]
